//
//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with $1$ and $2$, the first $10$ terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
//

namespace MathProblems
{
    public class Problem2 
    {
        // cannot exceed four million in value
        public static int maxNumber = 4000000;

        public static void Run() 
        {
            int newNumber = 1;

            int oldNumber = 0;
            int current;
            int sum = 0;
            

            while (newNumber <= maxNumber) 
            {
                current = oldNumber + newNumber;

                if (current % 2 == 0) 
                {
                    sum += current;
                }

                oldNumber = newNumber;
                newNumber = current;
            }

            FileMaker.CreateResponse("Solution 2", Convert.ToString(sum));

        }
        
        




    }
}